# Generated by Django 5.0.6 on 2024-06-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
